# Generated by Django 5.1.3 on 2024-12-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0002_comprador_producto_vendedor_delete_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='condicion',
            field=models.CharField(default=1232, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default=1231, max_length=30),
            preserve_default=False,
        ),
    ]
