# Generated by Django 5.1.3 on 2024-12-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registros', '0003_producto_condicion_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=60),
        ),
    ]
